apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: account
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: account
    spec:
      containers:
      - image: account:latest
        name: account
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources: {}
status: {}
